apiVersion: v1
kind: Service
metadata:
  name: core-business-service
  namespace: chiro-erp
  labels:
    app: core-business-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetport: 8080
    protocol: TCP
    name: http
  selector:
    app: core-business-service
---


