apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-service
  template:
    metadata:
      labels:
        app: pos-service
    spec:
      containers:
      - name: pos-service
        image: chiro-erp/pos-service:latest
        ports:
        - containerPort: 8080
