# API Gateway Configuration for Consolidated Services
quarkus:
  http:
    port: 8080
    cors:
      ~: true
      origins: "*"
      methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
      headers: "Content-Type,Authorization,X-Requested-With"

# Service Discovery Configuration
gateway:
  services:
    core-business:
      name: "core-business-service"
      url: "http://core-business-service:8081"
      health-check: "/q/health"
      paths:
        - "/api/finance/**"
        - "/api/sales/**"
        - "/api/inventory/**"
        - "/api/procurement/**"
        - "/api/manufacturing/**"
    
    operations-management:
      name: "operations-management-service"
      url: "http://operations-management-service:8082"
      health-check: "/q/health"
      paths:
        - "/api/project/**"
        - "/api/fleet/**"
        - "/api/pos/**"
        - "/api/fieldservice/**"
        - "/api/repair/**"
    
    customer-relations:
      name: "customer-relations-service"
      url: "http://customer-relations-service:8083"
      health-check: "/q/health"
      paths:
        - "/api/crm/**"
    
    platform-services:
      name: "platform-services"
      url: "http://platform-services:8084"
      health-check: "/q/health"
      paths:
        - "/api/analytics/**"
        - "/api/notifications/**"
        - "/api/tenants/**"
        - "/api/billing/**"
    
    workforce-management:
      name: "workforce-management-service"
      url: "http://workforce-management-service:8085"
      health-check: "/q/health"
      paths:
        - "/api/hr/**"
        - "/api/users/**"

  # Circuit Breaker Configuration
  circuit-breaker:
    failure-threshold: 5
    recovery-timeout: 30s
    
  # Rate Limiting
  rate-limiting:
    requests-per-minute: 1000
    burst-size: 100

  # Load Balancing
  load-balancing:
    strategy: "round-robin"
    health-check-interval: 30s
