apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
      - name: user-management-service
        image: chiro-erp/user-management-service:latest
        ports:
        - containerPort: 8080
