apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurement-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: procurement-service
  template:
    metadata:
      labels:
        app: procurement-service
    spec:
      containers:
      - name: procurement-service
        image: chiro-erp/procurement-service:latest
        ports:
        - containerPort: 8080
