apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleet-service
  template:
    metadata:
      labels:
        app: fleet-service
    spec:
      containers:
      - name: fleet-service
        image: chiro-erp/fleet-service:latest
        ports:
        - containerPort: 8080
