apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-services
  namespace: chiro-erp
  labels:
    app: platform-services
    version: v1
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: platform-services
  template:
    metadata:
      labels:
        app: platform-services
        version: v1
    spec:
      containers:
      - name: platform-services
        image: chiro-erp/platform-services:latest
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: QUARKUS_HTTP_PORT
          value: "8083"
        - name: QUARKUS_PROFILE
          value: "prod"
        - name: MODULES
          value: "analytics, notifications, tenant-management, billing"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /q/health/started
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
      restartPolicy: Always
---