global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/q/metrics'
    scrape_interval: 30s

  # User Management Service
  - job_name: 'user-management'
    static_configs:
      - targets: ['user-management-service:8080']
    metrics_path: '/q/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Docker containers
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: containers
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dockerswarm_container_label_com_docker_compose_service]
        target_label: service
