apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
      - name: sales-service
        image: chiro-erp/sales-service:latest
        ports:
        - containerPort: 8080
