apiVersion: v1
kind: Service
metadata:
  name: platform-services
  namespace: chiro-erp
  labels:
    app: platform-services
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetport: 8083
    protocol: TCP
    name: http
  selector:
    app: platform-services
---

