apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: chiro-erp/inventory-service:latest
        ports:
        - containerPort: 8080
