apiVersion: apps/v1
kind: Deployment
metadata:
  name: repair-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repair-service
  template:
    metadata:
      labels:
        app: repair-service
    spec:
      containers:
      - name: repair-service
        image: chiro-erp/repair-service:latest
        ports:
        - containerPort: 8080
