apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
      - name: project-service
        image: chiro-erp/project-service:latest
        ports:
        - containerPort: 8080
