apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
    tier: application
    service: gateway
data:
  application.yml: |
    server:
      port: 8080
    spring:
      application:
        name: api-gateway
      profiles:
        active: kubernetes
      datasource:
        url: jdbc:postgresql://postgres:5432/chiro_erp
        username: chiro
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
      redis:
        host: redis
        port: 6379
      kafka:
        bootstrap-servers: kafka:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          group-id: api-gateway
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    logging:
      level:
        com.chiro: INFO
        org.springframework: WARN
        org.hibernate: WARN
