apiVersion: apps/v1
kind: Deployment
metadata:
  name: workforce-management-service
  namespace: chiro-erp
  labels:
    app: workforce-management-service
    version: v1
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: workforce-management-service
  template:
    metadata:
      labels:
        app: workforce-management-service
        version: v1
    spec:
      containers:
      - name: workforce-management-service
        image: chiro-erp/workforce-management-service:latest
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: QUARKUS_HTTP_PORT
          value: "8085"
        - name: QUARKUS_PROFILE
          value: "prod"
        - name: MODULES
          value: "hr, user-management, tenant-management"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /q/health/started
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
---
