apiVersion: apps/v1
kind: Deployment
metadata:
  name: manufacturing-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manufacturing-service
  template:
    metadata:
      labels:
        app: manufacturing-service
    spec:
      containers:
      - name: manufacturing-service
        image: chiro-erp/manufacturing-service:latest
        ports:
        - containerPort: 8080
