apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  namespace: chiro-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
      - name: finance-service
        image: chiro-erp/finance-service:latest
        ports:
        - containerPort: 8080
